### ISSUE TITLE
Q4 mid-quarter OKR scores

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/team-mgmt#14]
For libp2p KR owners:  @vyzo @marten-seemann @tomaka @bigs @Stebalien @jacobheun @vasco-santos @raulk @jhiesey 

Wednesday is the deadline for mid-quarter scoring of OKRs.  Could you pop into the [OKR spreadsheet](https://docs.google.com/spreadsheets/d/1BYwmbVicgo6_tOHAbgiUXWge8Ej0qR1M_gAUulazmrg/edit#gid=0) and put mid-quarter score estimates on each item you own?  Not just the P0's; this time let's score everything even though many will be zeros.

**Comment by bigs** [comment]
set!

**Comment by marten-seemann** [comment]
Done!

**Comment by Stebalien** [comment]
Done.

**Comment by vasco-santos** [comment]
All done!

**Comment by vyzo** [comment]
done.
