### ISSUE TITLE
Decision on peer IDs, CIDs, multibase, and ed25519

### ISSUE THREAD

**Issue by Stebalien** [libp2p/team-mgmt#15]
So, the issue of peer IDs came to a head today when I learned that OpenBazaar can't update to the latest libp2p because we've started auto-inlining ed25519 keys into peer IDs (changing the peer ID format for anyone using ed25519 keys).

We *also* need to support:

* Arbitrary hash functions. This means we really need some field in the key to specify the hash function.
* Multibase. Browsers need this for IPNS.

I have three concrete proposals on how to attack this but we need to make a decision:

* multibase-peer-IDs: https://github.com/libp2p/specs/issues/111#issuecomment-438849828
* CID-peer-IDs (text only): https://github.com/libp2p/specs/issues/111#issuecomment-438851849
* CID-peer-IDs (everywhere): https://github.com/libp2p/specs/issues/111#issuecomment-438873680

This hasn't gotten anywhere after years (?) of grumbling on GitHub so I'd like to schedule a synchronous call to make a final decision: are we going to use CIDs as peer IDs or not.

In addition to the libp2p team, @whyrusleeping and @daviddias really need to show up.

**Comment by daviddias** [comment]
CID-peer-IDs FTW
