### ISSUE TITLE
Recurring Sync Meeting

### ISSUE THREAD

**Issue by bigs** [libp2p/team-mgmt#16]
Inspired by the go and js core weekly meetings, we're moving the libp2p biweekly meeting to a format where a fresh notepad is posted on this thread in advance, so libp2p contributors who can't make the call can share their updates.

**Comment by bigs** [comment]
# 2018-12-03 libp2p Biweekly Update

[Cryptpad](https://cryptpad.fr/code/#/2/code/edit/wGiR5h9F8qSnasDcxaFwZyk+/)
[Zoom](https://www.google.com/url?q=https%3A%2F%2Fprotocol.zoom.us%2Fj%2F508697396)

**Comment by bigs** [comment]
# 2019-01-14 libp2p Biweekly Update
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/jcShiJsVxIYG+SPmAxjv0E2Y/)
- [Zoom](https://zoom.us/j/606750881)

(Sorry this was put up so late!)

**Comment by bigs** [comment]
sorry for the delay here...

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/auM5VdxboEfQHixutkYFBNSF/)
- [Zoom](https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F606750881)

matt, we can catch up with your update later!

**Comment by anacrolix** [comment]
Is it worth posting the next meeting links now?

**Comment by bigs** [comment]
# 2019-02-11 libp2p Biweekly Update

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/pJsojwpknxZ-Yen5YuCMh6ai/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by dryajov** [comment]
Anyway to set up a community calendar reminder for this, it's common practice for the other ipfs/libp2p calls.

**Comment by mgoelzer** [comment]
@dryajov 

Yes, there's a recurring calendar event ([link](https://calendar.google.com/event?action=TEMPLATE&tmeid=NDV0MGFlMmJlYnNyaHBkMGI4M3NqMG5nZGdfMjAxOTAyMTFUMTgzMDAwWiBsaWJwMnAuaW9fMHE5NjgyaTN0ZTdlYW5oZTlxN2FlMWM1OGdAZw&tmsrc=libp2p.io_0q9682i3te7eanhe9q7ae1c58g%40group.calendar.google.com&scp=ALL)) on this repo's README.md.

The event is from the [libp2p Public Events](https://calendar.google.com/calendar?cid=bGlicDJwLmlvXzBxOTY4MmkzdGU3ZWFuaGU5cTdhZTFjNThnQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) calendar, which people can also add in their calendar software.  Other than the bi-weekly call, there are not a lot of libp2p public events currently.  But that may change in the future.

**Comment by bigs** [comment]
# 2019-02-25 libp2p Biweekly Update

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/W3mzACOZDBDOFvxj2nOyPN5f/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-03-04

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/vFW9dTSSXBRXuL385lXvR69A/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-03-11 libp2p Weekly Update

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/pzEs1xyaIfbbwJG3FlL1hqHq/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-03-25 libp2p Weekly Update

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/XPdaLEs+KQCZnPVtFWOdBb6d/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-04-01 libp2p Weekly Update
_Ed's note: I acknowledge that it's pretty poor timing to start the new chapter of our meeting on April 1st, but this is **really** happening!_

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/fPrUkw1XxTOLHNOlIqSuzT1X/)
- [Zoom](https://protocol.zoom.us/j/696673995)

**Comment by jacobheun** [comment]
# 2019-04-08 libp2p Weekly Update 5:30pm UTC

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/MS3s3PIC4RiLHR+LjvvJUvFi/)
- [Zoom](https://protocol.zoom.us/j/696673995)

**Comment by jacobheun** [comment]
# 2019-04-22 libp2p Weekly Update 5:30pm UTC

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/8c5dtVh-+XSxwLvST2jMIr3D/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-04-29 libp2p weekly sync (australian friendly edition)

_Note: I am on vacation this week and nominate @anacrolix to lead! Further note, this event is not recurring on my calendar and I don’t know the exact UTC time._

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/WznIfYMEX0FJShd4afAyJVjD/)
- [Zoom](https://protocol.zoom.us/j/696673995)

**Comment by bigs** [comment]
# 2019-05-06 libp2p weekly sync (5:30pm UTC)
 _Ed's note: Got back from vacation quite late last night, sorry for the delay. In general these posts will be up much sooner!_

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/jIN0uvlJ3nLTzGHW0i1o+h8t/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2910-05-13 libp2p weekly sync (technically 01:00AM UTC on 5/14)

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/bJkGhMizdSx4m5zVWPHIL5xl/)
- [Zoom](https://protocol.zoom.us/j/696673995)

**Comment by bigs** [comment]
# 2019-05-20 libp2p weekly sync (5:30pm UTC)
_Last week being skipped through off the planning!_

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/oTnzdtF7WtcOI5IjYAgj-aoZ/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-05-27 libp2p weekly sync (1:00AM UTC on 5/28)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/HuwskECs4FMQ+gNSXCpV7h+A/)
- [Zoom](https://protocol.zoom.us/j/696673995)

# 2019-06-02 libp2p weekly sync (5:30PM UTC)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/osjrrH-zqSUTwi3qU+R+nrij/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-06-10 libp2p weekly sync (1:00AM UTC on 2019-06-11)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/nJ7modzSbFSCYciU222MjFIq/)
- [Zoom](https://protocol.zoom.us/j/696673995)

# 2019-06-17 libp2p weekly sync (5:30PM UTC)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/H0nkydomCZyP2GvfZqeY5H0I/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-06-24 libp2p weekly sync (1:00AM UTC on 2019-06-25)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/3UCc3J182t0PXB2wjRQ-OVGX/)
- [Zoom](https://protocol.zoom.us/j/6966739950

# 2019-07-01 libp2p weeklyn sync (5:30PM UTC)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/FjLwGZQZOwwq3EH7U+QBa0mK/)
- [Zoom](https://zoom.us/j/606750881)

**Comment by mgoelzer** [comment]
# 2019-07-01 libp2p weeklyn sync (5:30PM UTC)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/j6Q4WzXQxca4-YW7s3D1MMmb//)
- [Zoom](https://zoom.us/j/606750881)

**Comment by bigs** [comment]
# 2019-07-15 libp2p weekly sync (5:30PM ETC)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/2A+Zz5GWapWpcuy7FclpDEAZ/)
- [Zoom](https://zoom.us/j/606750881)

# 2019-07-22 libp2p weekly sync (1:00AM UTC on 2019-07-23)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/QCZz-Rion5FKcxO-MTHaY8NS/)
- [Zoom](https://protocol.zoom.us/j/6966739950)

**Comment by daviddias** [comment]
Folks, the current calendar event points to https://github.com/libp2p/pm/tree/master/agendas for Agenda, and the document found there seems deserted since 2018. Can the owner of the libp2p Public Events Google Calendar update it so that it doesn't confuse users?

**Comment by mgoelzer** [comment]
Yeah, that was outdated.  I opened a PR to fix it (
https://github.com/libp2p/team-mgmt/pull/43)

Mike

**Comment by bigs** [comment]
# 2019-07-29 libp2p weekly sync (5:30PM UTC)
- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/J7yOczStwMu2A5ZYRca08Wic/[)

# 2019-08-05 libp2p weekly sync (1:00AM UTC on 2019-08-06)
- [Zoom](https://protocol.zoom.us/j/6966739950)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/3oZXay-A+IEXRGy1d7cjJGeR/)

**Comment by bigs** [comment]
_Sorry, was on vacation - Ed_

# 2019-08-12 libp2p weekly sync (5:30PM UTC)
- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/Lp2L4L+jrOGW9FKq0HswMeVX/)

# 2019-08-19 libp2p weekly sync (1:00AM UTC on 2019-08-20)
- [Zoom](https://protocol.zoom.us/j/6966739950)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/8zpSBjnZSVmxsYJLXgw7Xp5B/)

**Comment by bigs** [comment]
# 2019-09-09 libp2p weekly sync (5:30PM UTC)
- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/tWPmEk1w-yLxkbDrryYajGuA/)

# 2019-09-16 libp2p weekly sync (1:00AM UTC on 2019-09-17)
- [Zoom](https://protocol.zoom.us/j/6966739950)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/rliKKHsKmHYFRZbsRSHIEnP5/)

**Comment by mgoelzer** [comment]
# 2019-09-23 libp2p weekly sync (5:30PM UTC)
- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/TpsseurJEyZoOaagNUxj7OJ3/)

**Comment by bigs** [comment]
# 2019-10-07 libp2p weekly sync

- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/m1OH30SehqijRcxhE4UQ86u8/)

**Comment by bigs** [comment]
# 2019-10-21 libp2p weekly sync

- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/g2QtDWZP6sHQGwZk3fRZw9wo/)

**Comment by bigs** [comment]
# 2019-10-28 libp2p weekly sync
- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/nU3Z3Ea5wWzNhyRAXCN4ylWm/)

**Comment by bigs** [comment]
# 2019-11-04 libp2p weekly sync
- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/T155y5pyf65uoQN2BIxQ2lqg/)

**Comment by bigs** [comment]
# 2019-11-11 libp2p weekly sync

- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/b2OXLeUmR4XUaov59hxqqe7B/)

**Comment by bigs** [comment]
# 2019-11-25 libp2p weekly sync

- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/El7KEkyJUgObQpiRGnKtx4Pj/)

**Comment by jacobheun** [comment]
# 2019-12-02 libp2p weekly sync

- [Zoom](https://zoom.us/j/606750881)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/QrMtxIT8Dz39mH6tLbzKGPRA/)

**Comment by jacobheun** [comment]
## Monday December 09, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/ODAPo4YKyMMM1ZYTc0tkiTxU/)

**Comment by jacobheun** [comment]
## Monday December 16, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/91tdvp5ryiOKcS8MBSuA06x6/)

**Comment by jacobheun** [comment]
## Monday January 6, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/8EduUiGfuJyxEa8Lp8PqiHt-/)

**Comment by jacobheun** [comment]
## Monday January 13, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/irZWTrVJYakh0kvQwutD2w3I/)

**Comment by jacobheun** [comment]
## Monday January 20, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/ydFwjPFc8bpjkDctQThIhOyk/)

**Comment by jacobheun** [comment]
## Monday January 27, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/SD1129gPP-zUwvCL7PvszFWR/)

**Comment by jacobheun** [comment]
## Monday February 03, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/uslIwNRNRbIo4g2RUaK1ISd9/)

**Comment by jacobheun** [comment]
## Monday February 10, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/WmZumrGq4vy0v6NcLENRmQW4/)

**Comment by jacobheun** [comment]
## Monday February 24, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/bRx+AiX3OBnEHSjXnj4ILXWT/)

**Comment by jacobheun** [comment]
## Monday March 02, libp2p weekly sync 6:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/DVQpphn6qD83VFJJchJ9yQVv/)

**Comment by yusefnapora** [comment]
## Monday March 02, libp2p weekly sync 5:30PM UTC

Note that the meeting has shifted an hour earlier due to US Daylight Savings time changes!

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/zEFRew9eKbGo7Po+MgqNyBA0/)

**Comment by jacobheun** [comment]
## [Canceled, Async Updates Only] Monday March 16, libp2p weekly sync ~~5:30PM UTC~~

Several members of the libp2p team will be unavailable today so we will not be meeting. The Cryptpad has been posted for async, weekly updates. 

- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/N59s8GRfcaRpu+pb12tX56Pr/)

**Comment by jacobheun** [comment]
## Monday March 23, libp2p weekly sync 5:30PM UTC

_Note that the meeting has shifted an hour earlier due to US Daylight Savings time changes!_

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/yscKjzxdspStEG-DLLdQC0zb/)

**Comment by jacobheun** [comment]
## [Canceled] Monday March 30, libp2p weekly sync

Several members of the libp2p team will be unavailable for the sync today so it has been **canceled**. See everyone next week at 6:30PM UTC!

**Comment by jacobheun** [comment]
## Monday April 06, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/GOUnZ22oeqIS8H6uCWVRGGSq/)

**Comment by yusefnapora** [comment]
## Monday April 13, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/2JakZf5vCcYXgDCTOWeApsd1/)

**Comment by jacobheun** [comment]
## Monday April 20, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/7T0z88NmhTKQ2jlpY+nE7JN5/)

**Comment by jacobheun** [comment]
## Monday April 27, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/hzbg2cD3c9EkIEjdVILMC24V/)

**Comment by jacobheun** [comment]
## Monday May 4, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/n8nQyKcSegNQQwJveRuz50rT/)

**Comment by jacobheun** [comment]
## [Cancelled] Monday May 11, libp2p weekly sync

A majority of the libp2p core team will not be available for the weekly sync on Monday, May 11th, so the sync has been cancelled. See everyone on the 18th!

**Comment by yusefnapora** [comment]
## Monday May 18, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/l+V7hVGPIyEhc7R45ABdNBCh/)

**Comment by jacobheun** [comment]
## Monday May 25, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/evVOW6tSwITH7Vz8MSZJBHMl/)

**Comment by jacobheun** [comment]
## Monday June 1, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/ulYAh2kHB21Bj5TqgJydDtOC/)

**Comment by jacobheun** [comment]
## Monday June 08, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/IjmXalwRjEwehw3bw0bmaD2-/)

**Comment by jacobheun** [comment]
## Monday June 15, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/YeXiz8fTLmrpsdGSzOAsJ1jZ/)

**Comment by jacobheun** [comment]
## Monday June 22, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/3/code/edit/31ae8a0e1edb016d599e17ffd84b5ff4/)

**Comment by jacobheun** [comment]
Todays meeting, June 22, will consist of async updates only. We won't be meeting.

**Comment by jacobheun** [comment]
## Monday June 29, libp2p weekly async updates

- [Cryptpad](https://cryptpad.fr/code/#/2/code/view/k8oAWTpxsgHjnDhwz9r5Mlsb6W4gDrcIPembJxFrJcw/)

We will be doing async updates only again this week. 

_Note_: We are currently working on evaluating the future of this meeting to provide better channels for collaborating with the core team., and gaining a better view into the latest/upcoming libp2p efforts.

**Comment by jacobheun** [comment]
## Monday July 06, libp2p weekly sync 5:30PM UTC

- [Zoom](https://protocol.zoom.us/j/6314780661)
- [Cryptpad](https://cryptpad.fr/code/#/2/code/edit/07NEWj-NXlETgEatNVT0ymaf/)

**Comment by jacobheun** [comment]
We are cancelling this meeting going forward and will be transitioning to an aggregate post on the libp2p forums, https://discuss.libp2p.io. 

The goal here is to provide a better forum for asynchronously creating and collaborating on what's going on in libp2p, a synchronous meeting that is outside of the normal hours of a lot of community members is not a good forum for this.
