### ISSUE TITLE
 Code Issues 26 Pull requests 8 Actions Insights Circle CI v2.0 migration

### ISSUE THREAD

**Issue by mburns** [libp2p/team-mgmt#25]
related to https://github.com/ipfs/team-mgmt/issues/879

There is a deadline to either deprecate or upgrade from the Circle 1.0 platform.

Repos impacted:
 - [x] https://github.com/libp2p/interface-peer-discovery/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-iprs-record/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-libp2p-distributed-record-store/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-libp2p-kad-record-store/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-libp2p-kad-routing/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-libp2p-mplex/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-libp2p-nat-mngr/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-libp2p-tcp/blob/master/circle.yml
 - [x] https://github.com/libp2p/js-libp2p-utp/blob/master/circle.yml
 ~~- [ ] https://github.com/libp2p/js-spdy-stream-muxer/blob/master/circle.yml~~ Repo is Archived

**Comment by jacobheun** [comment]
circle ci should be removed from the js modules, we are currently migrating everything to Travis CI only. I'll take this on.
