### ISSUE TITLE
Libp2p public events calendar: Sync meeting is still named "by-weekly"

### ISSUE THREAD

**Issue by mkg20001** [libp2p/team-mgmt#52]
While the event is occurring weekly, it's name is still by-weekly

**Comment by jacobheun** [comment]
@mgoelzer @bigs do either of you have perms to correct the calendar event title?

**Comment by bigs** [comment]
I believe @mgoelzer does!

**Comment by jacobheun** [comment]
This has been corrected on the calendar to "libp2p Weekly Sync"
